# Generated by Django 4.2.7 on 2024-05-11 09:38

from django.db import migrations, models
import emailApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Username')),
                ('last_name', models.CharField(max_length=20)),
                ('contact_info', models.CharField(max_length=10, unique=True, validators=[emailApp.models.contactVal])),
            ],
        ),
    ]
