# Generated by Django 4.2.7 on 2024-05-11 11:17

from django.db import migrations, models
import emailApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('emailApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='contact_info',
            field=models.CharField(max_length=11, unique=True, validators=[emailApp.models.contactVal]),
        ),
    ]
